# 工作流名称
name: Sync-Images-to-Tencentyun-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to Tencentyun.
# 怎样触发工作流
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      registry:
        description: "docker registry"
        required: true
        default: "docker.io"
      imagePath:
        description: "镜像路径"
        required: true
        default: "library/python:3.10-slim-bullseye"
      imageName:
        description: "镜像名称"
        required: true
        default: "python:3.10-slim-bullseye"  

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
        
    - name: Use Skopeo Tools Sync Image to Tencentyun Hub
      run: |
        #!/usr/bin/env bash
        docker login hkccr.ccs.tencentyun.com --username=${{ secrets.TENCENT_USERNAME }} --password=${{ secrets.TENCENT_PASSWORD }}
        skopeo login -u ${{ secrets.TENCENT_USERNAME }} -p  ${{ secrets.TENCENT_PASSWORD }} hkccr.ccs.tencentyun.com
        skopeo copy docker://${{ github.event.inputs.registry }}/${{ github.event.inputs.imagePath }} docker://hkccr.ccs.tencentyun.com/domi/${{ github.event.inputs.imageName }}
 
